### ISSUE TITLE
Unable to retrieve data from deconz

### ISSUE THREAD

**Issue by muppel2** [fixje/deflux#5]
Dear deflux team,

I have installed deflux on my RaspberrPi4 running on Raspbian (Bullseye).

When I try to acquire an API key or retrieve data from the websocket (after manually retrieving the API key using POSTMAN), deflux always reports an error:
```
time=2024-06-10T12:39:04.022+02:00 level=ERROR msg="Failed to fetch sensors: %s" !BADKEY="unable to decode deCONZ /sensors response: invalid character '<' looking for beginning of value"
```
or
```
time=2024-06-10T12:36:37.184+02:00 level=ERROR msg="Could not create websocket reader: %s" !BADKEY="unable to populate sensor cache: unable to decode deCONZ /sensors response: invalid character '<' looking for beginning of value"
```

My config files looks like:
```
deconz:
  addr: http://192.168.3.118:80/`
  apikey: "[snip]"
  wsaddr: "ws://192.168.3.118:443"
influxdb:
  url: http://localhost:8086
  token: [snip]
  org: CHI
  bucket: zigbee
fillvalues:
  enabled: false
  initialfill: true
  fillinterval: 30m0s
  lastseentimeout: 2h0m0s
```
(the port ":80" worked for the API key generation)

Go reports 
`go version go1.22.4 linux/arm64`

Is this a configuration mistake on my side or more an issue in deflux?

**Comment by rvk01** [comment]
Are you sure the wsaddr is correct? 
Why not just remove it and let the code auto-discover this by itself?

**Comment by muppel2** [comment]
Thank you for your quick reply!

That was my first try as well, but it failed (Deconz was open for new registrations at that moment):
```
/root/go/bin/deflux -config-gen

## deCONZ Gateway discovery failed: unable to parse json from discovery endpoint: invalid character '<' looking for beginning of value. Complete config manually.
## Could not pair with deconz: unable to send post request: Post "http://127.0.0.1:8080/api": dial tcp 127.0.0.1:8080: connect: connection refused
## Please add the API key manually
deconz:
  addr: http://127.0.0.1:8080/
  apikey: ""
  wsaddr: ""
influxdb:
  url: http://localhost:8086
  token: SECRET
  org: organization
  bucket: default
fillvalues:
  enabled: false
  initialfill: true
  fillinterval: 30m0s
  lastseentimeout: 2h0m0s
```
Deconz does not answer for me on Port :8080, only :80 - this it where I manually retrieved the auth key. is it possible to autodetect also on port :80 ?
